version: '3'

services:
  backend:
    container_name: pizzaria
    build: .
    restart: 'always'
    ports:
      - 3333:3333
    command: npm run dev
    volumes:
      - .:/usr/app
    depends_on:
      - db
  db:
    container_name: mysql
    image: mysql
    restart: "always"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mysql
      MYSQL_PASSWORD: mysql